### PR TITLE
add -r flag documentation to readme

### PR DESCRIPTION
**Pull request by DeepAnchor**
Your documentation for the -r flag is pretty decent, might as well add it to the readme.

#122

### CODE REVIEW

**Comment by ifraixedes** [comment]
+1 to merge it, it's not clear that the option exists

**Comment by jmervine** [comment]
+1

**Comment by freeformz** [comment]
+1, although I would expand the `go get` statement to include all `go *` tasks (e.g. `go test`).

**Comment by freeformz** [comment]
Thanks! Merging.

**Pull request merged**
