### PR TITLE
Add changelog

### PR DESCRIPTION
**Pull request by buddhamagnet**
Wondered if it would make sense to add a changelog so people can see what's included in each release? Happy to help maintain this is it's a help?

### CODE REVIEW

**Comment by freeformz** [comment]
Sure, care to update this and add a 'v' in front of the version? If you can back track this a little as well that would be good, but not 100% necessary.

**Comment by buddhamagnet** [comment]
Have done my best, not easy as the version bumps are not always contained in a single commit.

**Comment by buddhamagnet** [comment]
OK think that's pretty much it, let me know otherwise!

**Comment by freeformz** [comment]
@buddhamagnet looks great! I squashed them all down to a single commit and merged them. Thanks!

**Pull request closed without merging**
