### PR TITLE
Add doc on `godep save -r ./...`

### PR DESCRIPTION
**Pull request by jingweno**

### CODE REVIEW

**Comment by rafaeljusto** [comment]
+1

**Comment by dmitris** [comment]
lack of documentaiton on "godoc save -r" creates confusion among users - see https://go-review.googlesource.com/#/c/8969/ for an example (review comment: "As I understand it, godep is a not a vendoring tool in the sense described in the faq (although it copies the source code, it does so by manipulating $GOPATH, not by rewriting import paths).")

**Comment by freeformz** [comment]
I think I've effectively closed this with ba35b97d0db08d8d57599079d99b65add0282b4e.

Please let me know (new PR / Issue) if we should do anything more.

Thanks!

**Pull request closed without merging**
