### PR TITLE
Skip download if ImportPath prefix has been seen

### PR DESCRIPTION
**Pull request by sttts**
The restore code looks up the repo root via `vcs.RepoRootForImportPath` for each imported package. If there are many (literally hundreds in our case) sub-packages of the same dependency, this code looks up the repo root again and again. If the dependency is on a non-known domain (e.g. `k8s.io/kubernetes` in contrast to `github.com/foo/bar`), this leads to one `go get` per sub-package, i.e. one http connection to get the meta data per sub-package. This is slow, very slow.

### CODE REVIEW

**Comment by ericchiang** [comment]
FYI this change also dramatically reduces the memory usage of `godep restore` (~3 GB) when using it against the Kubernetes repo.

**Comment by philips** [comment]
cc @thockin

**Comment by thockin** [comment]
Good to know, but I won't have time to futz with glide any time soon.

**Comment by freeformz** [comment]
I am closing this PR because the repo is going to be archived.

**Pull request closed without merging**
