### PR TITLE
very rough implementation of an "outdated' command - [WIP]

### PR DESCRIPTION
**Pull request by awsmsrc**
Hey there,

I'm working on some automated QA, security and code review tools.
I wanted to know which dependencies were out of date and more specifically what had changed and why (e.g if its just typos and refactors I'm not too fussed but if it is a security bug I want to know).

I only just got this working, the code is very rough. I didn't want to waste too much time if you didn't think it was a good idea or wouldn't get merged.

Thanks for the awesome tool either way :)

### CODE REVIEW

**Comment by awsmsrc** [comment]
Example output thus far

```
[luke:/Users/ … /go/src/github.com/awsmsrc/godep] feature/outdated_command 1 ± godep outdated
# cd /Users/luke/go/src/golang.org/x/tools/go/vcs; git diff 1cdaff4a02c554c9fb39dda0b56241c5f0949d91
fatal: bad object 1cdaff4a02c554c9fb39dda0b56241c5f0949d91
github.com/kr/pretty
github.com/kr/text
github.com/pmezard/go-difflib/difflib
golang.org/x/tools/go/vcs
[luke:/Users/ … /go/src/github.com/awsmsrc/godep] feature/outdated_command ± godep outdated github.com/kr/pretty
godep: commit e6ac2fc51e89a3249e82157fa0bb7a18ef9dd5bb
Author: Marc-Antoine Ruel <maruel@chromium.org>
Date:   Wed May 20 12:35:14 2015 -0400

    Run 'gofmt -w -s' on sources

commit cb0850c1681cbca3233e84f7e6ec3e4c3f352085
Merge: f31442d e559492
Author: Cameron Walters (cee-dub) <cameron.walters@gmail.com>
Date:   Mon Jan 19 14:12:28 2015 -0800

    Merge pull request #20 from gpaul/master

    kr/pretty: fix invalid heap pointer bug in tests.

commit e5594928ca7b4d4dca5a99c8f388065f1a03a4db
Author: Gustav Paul <gustav.paul@gmail.com>
Date:   Mon Jan 19 10:11:27 2015 +0000

    kr/pretty: fix invalid heap pointer bug.

    This fixes an issue with uintptr(1) being an invalid pointer.
    The test crashed when running with
    go test -cpu=4,4,4,4,4,4,4,4,4,4,4,4,4 github.com/kr/pretty
[luke:/Users/ … /go/src/github.com/awsmsrc/godep] feature/outdated_command ±
```

**Comment by freeformz** [comment]
Maybe we could combine this with the `diff` command somehow?  Or at the very least deprecate the diff command for this or something like it.

I'm hesitant to add another command atm w/o more thought into it's purpose and how it fits in long term. For instance. I'd like to have `godep get` fetch directly into the `vendor/` directory when VendorExperiment is on (with a switch to disable) ... how would this comment work then?

**Comment by awsmsrc** [comment]
The purpose is so that you can not only see what packages are outdated but by how much and more importantly what changed and why.

For example I don't need to update my package for some refactoring and typo fixes but if there are some security or performance patches then it is worth my time.

I'm working on some automated tooling that keeps track of dependencies and let's me know how outdated my dependencies are. This would allow me to create a report that was emailed to me on a weekly basis.

This was just an idea and I totally understand if you don't like it, which is why I didn't go too crazy with a polished implementation. I do believe this extra information is valuable to developers, especially in conjunction with automated tooling. There are some ui things to consider as well as there could be 1000s of commits, perhaps we could show tags as well

**Comment by client9** [comment]
hi @awsmsrc 

Love the idea, but IMHO probably best done as a separate package.

You also might like https://github.com/shurcooL/gostatus which is a completely different take on reporting of dependences. (cc @shurcooL )

I have a bunch of half-baked stuff, but we use this to make reports doing exactly what you suggested

   github.com/client9/gosupplychain/

In particular look at the  `github-behind command`.  It takes a `Godep` file and does something similar to what you are doing.   good: it doesnt mess-up your go path or need to do a restore or checkout big blobs of code.   bad: It's github specific

Here's sample:
```
github.com/client9/tlstext: ahead
    0 5bd8b72 badges
    1 0c2f760 badges
    2 1be66ac badges
    3 dd4ebd7 badges
    4 4afdf94 badges
github.com/cloudflare/ahocorasick: identical
github.com/daaku/go.zipexe: identical
github.com/fatih/camelcase: identical
github.com/fatih/structs: ahead
    0 24ec389 fix typos
    1 dd04eba Merge pull request #42 from shawnps/patch-2 fix typos
github.com/go-ini/ini: identical
github.com/go-ole/go-ole: ahead
    0 849646a implement ToValueArray()
    1 5005588 Merge branch 'master' of git://github.com/go-ole/go-ole
```

Free free to rip out anything here and use it.

regards,

n

**Comment by client9** [comment]
hi me again @awsmsrc

I'd be curious if you could make your report outside of godep using it's api.  I seem to recall a lot of good functionality wasn't made public or made into a package.

Maybe we could merge our projects.. really they should be different only in output since they are doing the same things. (i.e. just specific a template file to make different outputs).

happy to help in either way.

regards,

n

**Comment by shurcooL** [comment]
Thanks for mentioning `gostatus` here @client9, it's indeed very relevant.

I agree this can and should (at least initially) be done outside. If wanted, it can be later brought inside.

In addition to `gostatus`, I'd highly recommend @awsmsrc to take a look at [Go Package Store](https://github.com/shurcooL/Go-Package-Store#go-package-store--). It adds a visual presentation of commits on top of `gostatus` minimal output. It also supports a `-godeps` flag to specify a Godeps.json file to use as "base" versions, e.g.:

```bash
$ Go-Package-Store -godeps=/path/to/some/Godeps.json
Reading the list of Go packages from Godeps.json file: /path/to/some/Godeps.json
...
```

**Comment by freeformz** [comment]
@awsmsrc I totally get the point and it's something I like. I don't use `diff` much because frankly it's not useful enough to me. I think something like this could be more useful.

@shurcooL Nice packages/tools. I have been wanting to add something like `godep status` for a while to relay what godep thinks about the status of the project you are working on and it's dependencies. I think our licenses are compatible so I may look at "borrowing" some of that work. ;-) 

@client9 Godep has no real "api" atm, but I'm open to PRs / work to open one up.

**Comment by awsmsrc** [comment]
So how do you suggest we move forward from here?

**Comment by freeformz** [comment]
@awsmsrc `godep diff` already shows what's outdated (although perhaps a little more haphazardly than we'd like. How about altering the way that command works to work like this proposal? I think this would be more useful to people anyway.

**Comment by awsmsrc** [comment]
Works for me! My cat sat on my laptop and broke the screen (no seriously). So I'm out of action for a day or so whilst it gets repaired. Happy to work on this later or someone else can take what I did and take it a bit further

**Comment by freeformz** [comment]
@awsmsrc SGTM I have a bunch of other stuff scheduled for this week.

**Comment by shurcooL** [comment]
@freeformz Thanks. You're absolutely welcome to do that. If you look at Go-Package-Store, make sure to use the branch in this PR, it's a huge improvement in code quality over the current master. https://github.com/shurcooL/Go-Package-Store/pull/53 I'm hoping to have that merged into master soon, but just in case.

**Comment by freeformz** [comment]
@awsmsrc Are you still interested in working on this?

**Comment by freeformz** [comment]
Closing, please open a new issue (or re-open this one) if you are interested.

**Pull request closed without merging**
