### PR TITLE
Replace `go get`, further fix up error handling/reporting

### PR DESCRIPTION
**Pull request by freeformz**
Fixes another issue reported in #186 where an entire package is missing.

Don't bother restoring/downloading if already done.

### CODE REVIEW

**Comment by freeformz** [comment]
@ironcladlou This should solve the aws-sdk issue .... but there are some consistency issues with `github.com/openshift/origin` Godeps.json file. 

Some of them are duplicate shas for the same repo, one for package A another for package B in the same repo:
- https://github.com/openshift/origin/blob/0d4de0b1801e8c58a28c8bcd9d12b5d0c46de1cb/Godeps/Godeps.json#L744-L753
- https://github.com/openshift/origin/blob/0d4de0b1801e8c58a28c8bcd9d12b5d0c46de1cb/Godeps/Godeps.json#L876-L895
- 

Some appear to be shas from forks of the repos that are not on the canonical master (see #366).

There is at least once case where a recorded package is missing (looks to be in a [PR](https://github.com/kubernetes/kubernetes/pull/7893)) but is also recorded twice with 2 [different shas](https://github.com/openshift/origin/blob/0d4de0b1801e8c58a28c8bcd9d12b5d0c46de1cb/Godeps/Godeps.json#L1241-L1250).

**Comment by freeformz** [comment]
@eparis confirmed that this solves the docker/timeutils issues for you as well.

**Comment by freeformz** [comment]
https://github.com/docker/docker/pull/18685 for reference

**Comment by ironcladlou** [comment]
@freeformz Thanks for the analysis- I'm still working my way through the other problems, but was focused just on the sub package import issue.

I just verified that this commit fixes #186. Thanks again!

**Comment by eparis** [comment]
I can confirm this fixed my issue!

**Comment by tsaikd** [comment]
This patch cause an issue for me.

My build script is like this:
```sh
godep restore
go get
go build
```

example Godeps/Godeps.json:
```json
{
        "GoVersion": "go1.5",
        "Deps": [
                {
                        "ImportPath": "google.golang.org/appengine", 
                        "Rev": "58c0e2a2044a8d1abd8dd1d97939cd74497d0806"
                }
        ]
}
```

Then run build script in docker golang:1.5 (clean environment for GOPATH)

Error message:
```
godep: Dep (google.golang.org/appengine) restored, but was unable to load it with error:
    Unable to find dependent package github.com/golang/protobuf/proto in context of /go/src/google.golang.org/appengine
godep:  This may be because the dependencies were saved with an older version of godep (< v33).
godep:  Try `go get github.com/golang/protobuf/proto`. Then `godep save` to update deps.
godep: Error checking some deps.
```

But it worked well on v37 tools/godep@03595abb97a99e98133f9390b9c11e0aecf5f2e8

PS:
Why I don't list all dependence in Godeps.json ?
When I use some package, I don't care what it depend on.
I just use the top level API.
So if I write to Godeps.json, I should update often.
And all dependence in Godeps.json will cause it is hard to understand which package is necessary.

**Comment by freeformz** [comment]
@tsaikd What version of godep are you using? and if it's not the latest, is it still an issue with the latest version?

**Comment by tsaikd** [comment]
@freeformz I test from v45 to v38, all failed.
But v37 work.

I write a test Dockerfile if you want to verify
https://gist.github.com/tsaikd/710fa81c9ca409e7a62e

```
$ godep version && godep restore
godep v45 (darwin/amd64/go1.5.2)
godep: Dep (google.golang.org/appengine) restored, but was unable to load it with error:
	Package (github.com/golang/protobuf/proto) not found
godep: Error checking some deps.

$ godep version && godep restore
godep v44 (darwin/amd64/go1.5.2)
godep: Dep (google.golang.org/appengine) restored, but was unable to load it with error:
	Package (github.com/golang/protobuf/proto) not found
godep: Error checking some deps.

$ godep version && godep restore
godep v43 (darwin/amd64/go1.5.2)
godep: Dep (google.golang.org/appengine) restored, but was unable to load it with error:
	Package (github.com/golang/protobuf/proto) not found
godep: Error checking some deps.

$ godep version && godep restore
godep v42 (darwin/amd64/go1.5.2)
godep: Dep (google.golang.org/appengine) restored, but was unable to load it with error:
	Package (github.com/golang/protobuf/proto) not found
godep: Error checking some deps.

$ godep version && godep restore
godep v41 (darwin/amd64/go1.5.2)
godep: Dep (google.golang.org/appengine) restored, but was unable to load it with error:
	Unable to find dependent package github.com/golang/protobuf/proto in context of /Users/tsaikd/project/go/src/google.golang.org/appengine
godep: 	This may be because the dependencies were saved with an older version of godep (< v33).
godep: 	Try `go get github.com/golang/protobuf/proto`. Then `godep save` to update deps.
godep: Error checking some deps.

$ godep version && godep restore
godep v40 (darwin/amd64/go1.5.2)
godep: Dep (google.golang.org/appengine) restored, but was unable to load it with error:
	Unable to find dependent package github.com/golang/protobuf/proto in context of /Users/tsaikd/project/go/src/google.golang.org/appengine
godep: 	This may be because the dependencies were saved with an older version of godep (< v33).
godep: 	Try `go get github.com/golang/protobuf/proto`. Then `godep save` to update deps.
godep: Error checking some deps.

$ godep version && godep restore
godep v39 (darwin/amd64/go1.5.2)
godep: Dep (google.golang.org/appengine) restored, but was unable to load it with error:
	Unable to find dependent package github.com/golang/protobuf/proto in context of /Users/tsaikd/project/go/src/google.golang.org/appengine
godep: 	This may be because the dependencies were saved with an older version of godep (< v33).
godep: 	Try `go get github.com/golang/protobuf/proto`. Then `godep save` to update deps.
godep: Error checking some deps.

$ godep version && godep restore
godep v38 (darwin/amd64/go1.5.2)
godep: Dep (google.golang.org/appengine) restored, but was unable to load it with error:
	Unable to find dependent package github.com/golang/protobuf/proto in context of /Users/tsaikd/project/go/src/google.golang.org/appengine
godep: 	This may be because the dependencies were saved with an older version of godep (< v33).
godep: 	Try `go get github.com/golang/protobuf/proto`. Then `godep save` to update deps.
godep: Error checking some deps.
```

```
$ godep version && godep restore
godep v37 (darwin/amd64/go1.5.2)
```

**Comment by freeformz** [comment]
AFAICT your Godeps.json file is incomplete?

If I make a simple app that uses the appengine package my generated Godeps.json file looks like this:

```console
$ cat Godeps/Godeps.json
{
	"ImportPath": "github.com/freeformz/t365",
	"GoVersion": "go1.5",
	"Deps": [
		{
			"ImportPath": "github.com/golang/protobuf/proto",
			"Rev": "68415e7123da32b07eab49c96d2c4d6158360e9b"
		},
		{
			"ImportPath": "golang.org/x/net/context",
			"Rev": "0ab009005dc16437045369e823a35d1af6232b69"
		},
		{
			"ImportPath": "google.golang.org/appengine",
			"Rev": "54bf9150c922186bfc45a00bf9dfcb91a5063275"
		}
	]
}
```

Also: You do not need to do a `go get` after a `godep restore` as long as all of your deps are recorded (which `godep save` does).

**Comment by tsaikd** [comment]
For example, when I write a nodejs app, I just record necessary dependent packages that I used. Npm will fetch dependencies recursively. In appengine case, why I need to record protobuf? I don't use it. It's the second level dependency. About `go get` tool, it even forbid to import unused packages.

If my use case does not fit the philosophy, just igore it. I can choice the v37 in my project. It works well.

**Comment by freeformz** [comment]
Go is not node. The `google.golang.org/appengine` package uses `github.com/golang/protobuf/proto` and w/o it the code won't build. Godeps is about making builds repeatable. W/o that code vendored there may be times where I can build your code (I've seen npm go down and cause all sorts of problems where users could no longer deploy).

**Comment by DreadPirateShawn** [comment]
Still appears to be failing with godep version 51.

```
$ godep version
godep v51 (linux/amd64/go1.5.2)
```
```
$ godep restore
godep: error restoring dep (github.com/prometheus/client_golang/model): cannot find package "github.com/prometheus/client_golang/model" in any of:
	/usr/local/go/src/github.com/prometheus/client_golang/model (from $GOROOT)
	/highland/gocode/src/github.com/prometheus/client_golang/model (from $GOPATH)
godep: Error restoring some deps. Aborting check.
```
```
{
        "ImportPath": "github.com/GoogleCloudPlatform/heapster",
        "GoVersion": "go1.4.2",
        "Packages": [
                "./..."
        ],
        "Deps": [
                {
                        "ImportPath": "github.com/prometheus/client_golang/model",
                        "Comment": "0.4.0-1-g692492e",
                        "Rev": "692492e54b553a81013254cc1fba4b6dd76fad30"
                },
                {
                        "ImportPath": "github.com/prometheus/client_golang/prometheus",
                        "Comment": "0.4.0-1-g692492e",
                        "Rev": "692492e54b553a81013254cc1fba4b6dd76fad30"
                },
                {
                        "ImportPath": "github.com/prometheus/client_golang/text",
                        "Comment": "0.4.0-1-g692492e",
                        "Rev": "692492e54b553a81013254cc1fba4b6dd76fad30"
                },
                {
                        "ImportPath": "github.com/prometheus/client_model/go",
                        "Comment": "model-0.0.2-12-gfa8ad6f",
                        "Rev": "fa8ad6fec33561be4280a8f0514318c79d7f6cb6"
                },
                {
                        "ImportPath": "github.com/prometheus/procfs",
                        "Rev": "490cc6eb5fa45bf8a8b7b73c8bc82a8160e8531d"
                }
        ]
}
```

**Comment by freeformz** [comment]
@DreadPirateShawn I was able to reproduce this by synthetically checking out the affected package and running restore. Will look more: godep: error restoring dep (github.com/prometheus/client_golang/model): cannot find package "github.com/prometheus/client_golang/model" in any of:
	/usr/local/go/src/github.com/prometheus/client_golang/model (from $GOROOT)
	/Users/emuller/go2/src/github.com/prometheus/client_golang/model (from $GOPATH)

**Pull request merged**
