### PR TITLE
Add Go devel version workaround

### PR DESCRIPTION
**Pull request by zchee**
Signed-off-by: Koichi Shiraishi <zchee.io@gmail.com>

### CODE REVIEW

**Comment by barakmich** [comment]
+1 for this, or a similar fix. My Travis builds are failing because of this (testing against Go `tip`).

**Comment by freeformz** [comment]
Do you think we should record the sha?

```console
$ go version
go version devel +8d5ff2e Tue Dec 29 21:16:59 2015 +0000 darwin/amd64
```

Probably not worth the hassle. If you are using devel it will just always vary most likely.

**Comment by freeformz** [comment]
Thanks!

**Comment by zchee** [comment]
@freeformz Thanks merged.

> Do you think we should record the sha?
Yes. Since Golang recent change of cgo often, I also want sha.
Because I wanted to run test of travis, First it was pr only in 'devel'

**Pull request merged**
