### PR TITLE
Add "licence" (UK spelling) to list of possible license/legal files, plus bonus spelling corrections

### PR DESCRIPTION
**Pull request by client9**
Add "licence" (UK spelling) to list of possible license/legal files, plus bonus spelling corrections

Not urgent.

thanks for a great project.

n

### CODE REVIEW

**Comment by freeformz** [comment]
Please make sure to `go fmt` the code and I'll merge.

**Comment by client9** [comment]
hmm weird.  ok.

**Comment by client9** [comment]
done.

**Comment by freeformz** [comment]
This was merged in as 26e6c638845825cecd1addc3f03578c9977676bd. Thanks!

**Pull request closed without merging**
