### PR TITLE
Consider "AUTHORS" and "CONTRIBUTORS" legal files

### PR DESCRIPTION
**Pull request by aaronbee**
Some packages, such as github.com/tchap/go-patricia, have an AUTHORS
file to list the names of the copyright holders.

### CODE REVIEW

**Comment by 7AC** [comment]
LGTM

**Comment by freeformz** [comment]
This PR changes much more than that though. Please remove the other changes or describe why they were necessary.

**Comment by aaronbee** [comment]
My bad. I didn't mean to add those other changes to this PR.

**Comment by aaronbee** [comment]
I created a new PR: https://github.com/tools/godep/pull/522

**Pull request closed without merging**
