### PR TITLE
feature: added verbose flag to restore command

### PR DESCRIPTION
**Pull request by mariokostelac**
Restoring a big number of dependencies lasts for some time so it is nice to have some update about the progress.

### CODE REVIEW

**Comment by freeformz** [comment]
@mariokostelac Can you rebase this and I'll check it out?

**Comment by freeformz** [comment]
#152 is similar(ish) and merged. If you want to re-open a PR with cleaned up (or additional) output that would be great, but I'm going to close this for now.

**Comment by kr** [comment]
Did you mean #243? Looks like #153 is still open (but should be closed?).

**Comment by freeformz** [comment]
@kr Yeah. I did. I think I meant to reference both #152 and #243, but got distracted part of the way through. Thanks

**Pull request closed without merging**
