### PR TITLE
godep save: add -tags flag.

### PR DESCRIPTION
**Pull request by jnfeinstein**
I needed this for a project and couldn't find any previous efforts, so I attempted it myself.  I based this on the fact that `go list` seemed to work fine with the `-tags` flag.  I ran it with my project and godep produced the correct outputs.  Please let me know if this is useful and/or done correctly.

### CODE REVIEW

**Comment by maxpersson** [comment]
Will this be merged? I just added tag based configuration for the storage of my CQRS library https://github.com/looplab/eventhorizon, without the proper tag on save dependencies for the specified storage backend are missing.

**Comment by whazzmaster** [comment]
I'm also interested in this PR; I'd much rather use an official release rather than to fork it and apply the patch just to run goose on heroku.

**Comment by jsha** [comment]
For the Let's Encrypt project (letsencrypt.org), we depend on tags to generate the correct dependency graph for godep, so the main branch doesn't work for us. The pull request fixes a critical issue for us, so currently we have to tell developers to fetch and install this branch instead of the default godep. It would be really helpful if you could merge this, @kr!

Thanks,
Jacob

**Comment by freeformz** [comment]
@jnfeinstein Please rebase against master and I'll take a look.

**Comment by jnfeinstein** [comment]
@freeformz, the branch is rebased.  The only conflict was in the usage blurb.

**Comment by leehambley** [comment]
We just put an app into production, and we ran into this, we have conditional build-time metrics and analytics that rely on an external package (Rollbar), hidden behind builds tags, `godep` can't see it.

We've worked around it by importing the Rollbar package to `_` in a `// +build ignore` version of the file, which is less than ideal, since we still have to manually rewrite the import path in our `// +build release` file.

**Comment by freeformz** [comment]
Thanks @jnfeinstein. At this point I think we need to have the new exported method documented and a test case.

**Comment by kr** [comment]
I have hope that this can be solved without exposing additional knobs. The general approach I would take: godep should find all dependencies, ignoring `// +build` lines entirely. It should behave as if all build constraints are satisfied when finding imports. #84 has a little bit of discussion on this topic.

**Comment by freeformz** [comment]
@kr That probably makes the most sense in most circumstances.

although I do wonder if there is a case where the developer doesn't support building everything with a dep that uses a different build tag then the one they designed for.

**Comment by kr** [comment]
This approach wouldn't change what gets built, only what code is included in the repository.

**Comment by freeformz** [comment]
That is correct, but since it's vendoring everything regardless of `// +build` it could include something the developer didn't intent to include/support, which could then be triggered with a `-tag` by the builder.

Not sure if it matters though.

**Comment by kr** [comment]
> could then be triggered with a `-tag` by the builder

If that's the case, then the alternative is it wouldn't build at all for that builder.

It's still the responsibility of the person running `godep save` to at least glance at the diff to make sure it's reasonable, regardless of what godep does about tags.

**Comment by kr** [comment]
I suppose not building at can be preferable to including unsupported code for an unsupported build configuration. Hmmm.

**Comment by freeformz** [comment]
@jsha would it work for you guys if godep just included all the deps, ignoring `// +build` tags? Thereby punting the tagging off to those building the code later?

IMO this is the best solution.

**Comment by jsha** [comment]
@freeformz: That sounds like the best solution to me as well, thanks!

**Comment by freeformz** [comment]
Great I am going to close this then in favor of: #271

**Pull request closed without merging**
