### PR TITLE
Use vendor/ for updates if VendorExperiment

### LINKED ISSUE #250: `godep update` creates a _workspace directory even when GO15VENDOREXPERIMENT=1
I have the environment variable `GO15VENDOREXPERIMENT=1` set. When I initially ran `godep save` to get started, it created a `vendor/` directory as expected. However, when I went to update and ran

    godep update github.com/jacobsa/bazilfuse/...

this caused the directory `Godeps/_workspace/src/github.com/jacobsa/bazilfuse/` to be created, with the up to date contents, and the `vendor/` directory to be untouched.

I'm using godep at d8799f112f6c8dfe1e56142831bc3bb5c8796a0e.

### PR DESCRIPTION
**Pull request by freeformz**
This fixes #250

### CODE REVIEW

**Comment by freeformz** [comment]
@kr @neurogeek For your review.

**Comment by neurogeek** [comment]
lgtm

**Comment by freeformz** [comment]
@neurogeek Thanks!

**Comment by freeformz** [comment]
@kr Crap. Sorry I clicked the merge button. Habits. :-(

**Comment by kr** [comment]
Hah. :)

**Pull request merged**
