### PR TITLE
Verbose output for restore and get commands

### PR DESCRIPTION
**Pull request by zutherb**
Hi,

I had same trouble with godep because my ssh keys was not correct. godep was not able to show my that i could not get access to the repository rather. That's why i added verbose flag to the get and restore commands. I hope this helps someone else.

Regards
Bernd

### CODE REVIEW

**Comment by agileknight** [comment]
Any feedback on this?
Would be very useful to have a verbose option as it is easy to get into ssh access and other permission errors with private repos.

**Comment by kontrafiktion** [comment]
please merge

**Comment by freeformz** [comment]
I don't like the output of restore in verbose mode, but it's what get's output by go's tools/vcs stuff. We could clean that up later as I think this is helpful as is, modulo a few changes (which I'm just doing).

**Comment by freeformz** [comment]
Thanks! merged

**Pull request closed without merging**
